[package]
name = "apogee"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5"
hypertext = "0.6"
tracing-subscriber = "0.3"
tracing = "0.1"

[[bin]]
name = "site"
version = "0.1.0"
