name: Build site
on:
  pull_request:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GH_TOKEN }}
      - uses: cachix/cachix-action@v16
        with:
          name: luminite
          authToken: "${{ secrets.CACHIX_TOKEN }}"
      - run: |
          nix flake check
          nix build .#full --accept-flake-config
